//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopenhagenAirport
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOwner
    {
        public int Route_ID { get; set; }
        public string Airline { get; set; }
    
        public virtual Airline Airline1 { get; set; }
        public virtual FlightRoute FlightRoute { get; set; }
    }
}
